### ISSUE TITLE
Reading a GenericData$Record

### ISSUE THREAD

**Issue by stanfea** [damballa/abracad#11]
Hi,

I'm reading an avro file using a cascading.avro tap PackedAvroScheme.
I'm getting back a GenericData$Record.

Is there any way to use abracad to convert this from GenericData$Record => Clojure data structure?

I've been hunting around in the code but it seems like we need a decoder to be able to use the ClojureDatumReader

I don't really want to use JSON for performance reasons.

Thanks

**Comment by cddr** [comment]
I know this is a very old issue but I think I recently wrote some code that solves the problem faced by the OP in a way that might be acceptable to inclusion in this project.

https://github.com/cddr/edn-avro/blob/main/src/cddr/edn_avro.clj#L22

Any interest in a PR? Perhaps with slightly different naming? Like `as-generic-record` instead of `as-avro`? This would be very useful for Clojure folks trying to write kafka-streams apps who currently have to deal with the less than ideal avro converter provided by jackdaw.
