### ISSUE TITLE
encoding and decoding data, but not from a file?

### ISSUE THREAD

**Issue by xxx** [damballa/abracad#26]
Hi,

I'm wanting to use abracad with Apache Kafka, but it's not clear to me how to encode and decode in a way that isn't to a file.

I'd like to encode to and decode from the exact format that is produced by writing to a file with `data-file-writer` (i.e. binary encoded records with the schema included), but I'm not having any luck doing so.

It's also important to be able to specify a different schema on the reader side if necessary, to allow for schema evolution.

I did see #4, but encoding that way doesn't include the schema. Am I missing something here, or do I need to drop down into the Java implementation directly to do what I want?

thanks!

**Comment by llasram** [comment]
It depends!  At base Avro is a just collection of rules for data structures plus ways of encoding those structures.  The standard binary encoding is a compact encoding which assumes the decoder will have a copy of the schema available. Making the schema actually available is up to the application author. The standard "Avro data file" format is just a container format (itself actually a Avro record format!) which encapsulates both a schema (as JSON text) and structures encoded with that schema (in binary encoded format) with some details designed to make it easy to use with Hadoop MapReduce etc.

You have three basic options:

1. Use Avro data files as containers.  You can read/write data files against anything you adapt to the Avro  `SeekableInput` interface, including in-memory buffers.  The downside is that including the full schema as uncompressed text with each "message" if you aren't batching lots of Avro values together.  If you are so-batching then this is probably the easiest way to go.
2. Negotiate schemas out-of-band.  If your Avro values are going over some sort of communication channel which supports channel-level metadata, then you can just attach the writer schema to the channel.  This is the moral equivalent to what data files do for you under the hood.
3. Create your own compact per-value container.  This has come up a few times on the Avro ML etc, but has never seemed to produce anything official.  The basic idea is that you have some sort of schema repository, then you encode values as the pair of the (schema ID, actual value).  The "schema repository" could be as simple as in-code application-specific mapping, or an organization-wide network repository.  At Damballa we implemented something in-between we used to encode all HBase-stored Avro values, for which purpose I think it worked quite well.

I hope that helps!   But since I think your needs are out-of-scope for Abracad, I am closing this issue :-).  Feel free to re-open if I've misunderstood and there is something e.g. Java Avro does to solve your problem but Abracad does not expose from Clojure.

**Comment by xxx** [comment]
@llasram Thanks for getting back to me so fast!

I figured it out - I am new to Clojure and was not aware that `slurp` was assuming text, and there is no direct way to get it to read a file as binary without dipping into Java (AFAIK).

In case someone else runs into the same issue sometime, here's what I did:

I took [this StackOverflow answer](http://stackoverflow.com/a/26372677/340799) and used that instead:

```clojure
(defn- slurp-bytes
  "Slurp the bytes from a slurpable thing"
  [x]
  (with-open [out (java.io.ByteArrayOutputStream.)]
    (clojure.java.io/copy (clojure.java.io/input-stream x) out)
    (.toByteArray out)))

(defn read-employee-str
  [employee-str]
  (let [schema (parse-schema-filepath "schema/mpd-simple.avsc")]
    (with-open [adf (avro/data-file-reader schema employee-str)]
      (doall (seq adf)))))

(read-employee-str (slurp-bytes "mpd.out"))
```
