### ISSUE TITLE
Writing to Parquet file

### ISSUE THREAD

**Issue by saulshanabrook** [damballa/abracad#28]
I am trying to write to some Data to a [Parquet](https://parquet.apache.org/) file using this library. It [looks like I need a `GenericData$Record`](https://github.com/Parquet/parquet-mr/blob/fa8957d7939b59e8d391fa17000b34e865de015d/parquet-avro/src/test/java/parquet/avro/TestReadWrite.java#L216-L236) to write using in Parquet. Is there anyway I can turn use this library to turn Clojure data structures into this Record?

**Comment by saulshanabrook** [comment]
I think if I had an instance of`ClojureData` I could write this, because it inherits from `SpecificData`

**Comment by llasram** [comment]
The parquet-mr library appears to implement Avro integration directly in terms of the Avro API's `IndexedRecord` data objects instead of via a data model object such as abracad's `ClojureData`.  So I don't believe this is possible using the existing implementation.  If you want to write your own version which does use a data model, you can get the `ClojureData` singleton instance by calling `ClojureData/get` or a new instance by invoking the constructor.  You might also find it helpful to consider this [avro-mr commit](https://github.com/apache/avro/commit/854daafa0d91b3e0da986841ba6ad023eddddeca) adding such capability to that library, as well as the [parkour implementation](https://github.com/damballa/parkour/blob/master/src/clojure/parkour/io/avro.clj) utilizing it.

**Comment by saulshanabrook** [comment]
@llasram Thanks for looking into that. I think I will try the route of building a reader/writer for parquet directly for Clojure, skipping the Avro intermediary step, by extending `ReadSupport` and `WriteSupport`.

**Comment by gleisonsilva** [comment]
Hi, @saulshanabrook! Did you got manage this? I'm considering write some date to Parquet files, but, by now, I haven't found a  "easy/practical" way... can you point me some directions?

**Comment by saulshanabrook** [comment]
@gleisonsilva Yes I actually did! Taking a trip down memory lane... Here is the clojure code the writes directly to parquet:

https://github.com/saulshanabrook/ici.recorder/blob/6656c463614097af92017b3e52f5bbdbcff7e709/clojure/src/ici_recorder/parquet/write.clj

And for the larger context check out this blog post I wrote describing my process: https://medium.com/@saulshanabrook/data-at-hampshire-ici-8f0e0c064f14

Unfortunately I am not working on this anymore, but good luck!
